# Makefile
# (C) 2011 Akafugu
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.

MCU ?= attiny2313
F_CPU ?= 8000000L

TARGET = main

SRCS = main.c \
	button.c \
	led.c \
	usiTwiSlave.c

# These will automatically be checked and set 
VALUE_DEFS += 

# These will automatically be checked if they are set to YES
YESNO_DEFS += DEMO

